# NOTE: Changes to this file should also be applied to './test-windows.yml' and './test-translations.yml'

name: Node.js Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - translations

env:
  CI: true

jobs:
  test:
    runs-on: f64s
    timeout-minutes: 60

    steps:
      # Each of these ifs needs to be repeated at each step to make sure the required check still runs
      # Even if if doesn't do anything
      - name: Check out repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Setup node
        uses: actions/setup-node@56899e050abffc08c2b3b61f3ec6a79a9dc3223d
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm ci

      - name: Run build script
        run: npm run build

      - name: Run tests
        run: npx jest tests/content/
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
          
      - name: Run tests
        run: npx jest tests/rendering/
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
